name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.12'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Print partial environment variable
        run: |
          echo "DISCORD_CLIENT_ID first 5 chars: ${REACT_APP_DISCORD_CLIENT_ID:0:5}"
        shell: /usr/bin/bash -e {0}
        env:
          REACT_APP_DISCORD_CLIENT_ID: ${{ secrets.REACT_APP_DISCORD_CLIENT_ID }}

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm run build
        env:
          REACT_APP_DISCORD_CLIENT_ID: ${{ secrets.REACT_APP_DISCORD_CLIENT_ID }}
        shell: /usr/bin/bash -e {0}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          cname: eftdb.info
